### PR TITLE
Fix VM. Move context calls. Fix getCategories function.

### PR DESCRIPTION
**Pull request by Zidbrain**
1. Moved context calls from repository level to layout level.
2. Optimized getCategoriesString() function.
3. Fixed DetailsViewModel owner, so it would recreate with the fragment.

### CODE REVIEW

**Comment by RomanRad** [comment]
Hardcoded string - fun getCategoriesString(categories: List<String>): String =
        categories.joinToString(prefix = "Categories: ")

**Comment by RomanRad** [comment]
unnecessary code -  viewModel.news.observe(viewLifecycleOwner) {
            binding.news = it
        }

**Comment by RomanRad** [comment]
Use di to provide API - NewsRepository @Inject constructor() {
    private val client = OkHttpClient.Builder()
        .build()

**Comment by Zidbrain** [comment]
@RomanRad 
Done - #2
 


> unnecessary code - viewModel.news.observe(viewLifecycleOwner) { binding.news = it }

This is necessary in order to update the view on fragment recreation.

**Pull request merged**
